TEMPLATE	= app
LANGUAGE	= C++

INCLUDEPATH	+= .

HEADERS	+= hw.ui.h \
	ipc.h \
	hwconsts.h \
	team.h

SOURCES	+= main.cpp

FORMS	= hw.ui

TRANSLATIONS = hw_ru.ts

######################################################################
# Automatically generated by qmake (1.07a) ?? 11. ??? 20:42:14 2005
######################################################################


# Input
