/*
 * Hedgewars, a worms-like game
 * Copyright (c) 2005 Andrey Korotaev <unC0Rr@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 */

char sdlkeys[][2][16] = 
{
	{"mousel",	"mousel"},
	{"mousem",	"mousem"},
	{"mouser",	"mouser"},
	{"backspace",	"backspace"},
	{"tab",	"tab"},
	{"clear",	"clear"},
	{"return",	"return"},
	{"pause",	"pause"},
	{"escape",	"escape"},
	{"space",	"space"},
	{"!",	"!"},
	{"\"",	"\""},
	{"#",	"#"},
	{"$",	"$"},
	{"&",	"&"},
	{"'",	"'"},
	{"(",	"("},
	{")",	")"},
	{"*",	"*"},
	{"+",	"+"},
	{",",	","},
	{"-",	"-"},
	{".",	"."},
	{"/",	"/"},
	{"0",	"0"},
	{"1",	"1"},
	{"2",	"2"},
	{"3",	"3"},
	{"4",	"4"},
	{"5",	"5"},
	{"6",	"6"},
	{"7",	"7"},
	{"8",	"8"},
	{"9",	"9"},
	{":",	":"},
	{";",	";"},
	{"<",	"<"},
	{"=",	"="},
	{">",	">"},
	{"?",	"?"},
	{"@",	"@"},
	{"[",	"["},
	{"\\",	"\\"},
	{"]",	"]"},
	{"^",	"^"},
	{"_",	"_"},
	{"`",	"`"},
	{"a",	"a"},
	{"b",	"b"},
	{"c",	"c"},
	{"d",	"d"},
	{"e",	"e"},
	{"f",	"f"},
	{"g",	"g"},
	{"h",	"h"},
	{"i",	"i"},
	{"j",	"j"},
	{"k",	"k"},
	{"l",	"l"},
	{"m",	"m"},
	{"n",	"n"},
	{"o",	"o"},
	{"p",	"p"},
	{"q",	"q"},
	{"r",	"r"},
	{"s",	"s"},
	{"t",	"t"},
	{"u",	"u"},
	{"v",	"v"},
	{"w",	"w"},
	{"x",	"x"},
	{"y",	"y"},
	{"z",	"z"},
	{"delete",	"delete"},
	{"[0]",	"[0]"},
	{"[1]",	"[1]"},
	{"[2]",	"[2]"},
	{"[3]",	"[3]"},
	{"[4]",	"[4]"},
	{"[5]",	"[5]"},
	{"[6]",	"[6]"},
	{"[7]",	"[7]"},
	{"[8]",	"[8]"},
	{"[9]",	"[9]"},
	{"[.]",	"[.]"},
	{"[/]",	"[/]"},
	{"[*]",	"[*]"},
	{"[-]",	"[-]"},
	{"[+]",	"[+]"},
	{"enter",	"enter"},
	{"equals",	"equals"},
	{"up",	"up"},
	{"down",	"down"},
	{"right",	"right"},
	{"left",	"left"},
	{"insert",	"insert"},
	{"home",	"home"},
	{"end",	"end"},
	{"page up",	"page up"},
	{"page down",	"page down"},
	{"f1",	"f1"},
	{"f2",	"f2"},
	{"f3",	"f3"},
	{"f4",	"f4"},
	{"f5",	"f5"},
	{"f6",	"f6"},
	{"f7",	"f7"},
	{"f8",	"f8"},
	{"f9",	"f9"},
	{"f10",	"f10"},
	{"f11",	"f11"},
	{"f12",	"f12"},
	{"f13",	"f13"},
	{"f14",	"f14"},
	{"f15",	"f15"},
	{"numlock",	"numlock"},
	{"caps_lock",	"caps_lock"},
	{"scroll_lock",	"scroll_lock"},
	{"right_shift",	"right_shift"},
	{"left_shift",	"left_shift"},
	{"right_ctrl",	"right_ctrl"},
	{"left_ctrl",	"left_ctrl"},
	{"right_alt",	"right_alt"},
	{"left_alt",	"left_alt"},
	{"right_meta",	"right_meta"},
	{"left_meta",	"left_meta"},
	{"", ""}
};
