/*
 * Hedgewars, a worms-like game
 * Copyright (c) 2005 Andrey Korotaev <unC0Rr@gmail.com>
 *
 * Distributed under the terms of the BSD-modified licence:
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * with the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 * EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

char keys[][2][16] = 
{
	{"backspace",	"backspace"},
	{"tab",	"tab"},
	{"clear",	"clear"},
	{"return",	"return"},
	{"pause",	"pause"},
	{"escape",	"escape"},
	{"space",	"space"},
	{"!",	"!"},
	{"\"",	"\""},
	{"#",	"#"},
	{"$",	"$"},
	{"&",	"&"},
	{"'",	"'"},
	{"(",	"("},
	{")",	")"},
	{"*",	"*"},
	{"+",	"+"},
	{",",	","},
	{"-",	"-"},
	{".",	"."},
	{"/",	"/"},
	{"0",	"0"},
	{"1",	"1"},
	{"2",	"2"},
	{"3",	"3"},
	{"4",	"4"},
	{"5",	"5"},
	{"6",	"6"},
	{"7",	"7"},
	{"8",	"8"},
	{"9",	"9"},
	{":",	":"},
	{";",	";"},
	{"<",	"<"},
	{"=",	"="},
	{">",	">"},
	{"?",	"?"},
	{"@",	"@"},
	{"[",	"["},
	{"\\",	"\\"},
	{"]",	"]"},
	{"^",	"^"},
	{"_",	"_"},
	{"`",	"`"},
	{"a",	"a"},
	{"b",	"b"},
	{"c",	"c"},
	{"d",	"d"},
	{"e",	"e"},
	{"f",	"f"},
	{"g",	"g"},
	{"h",	"h"},
	{"i",	"i"},
	{"j",	"j"},
	{"k",	"k"},
	{"l",	"l"},
	{"m",	"m"},
	{"n",	"n"},
	{"o",	"o"},
	{"p",	"p"},
	{"q",	"q"},
	{"r",	"r"},
	{"s",	"s"},
	{"t",	"t"},
	{"u",	"u"},
	{"v",	"v"},
	{"w",	"w"},
	{"x",	"x"},
	{"y",	"y"},
	{"z",	"z"},
	{"delete",	"delete"},
	{"world 0",	"world 0"},
	{"world 1",	"world 1"},
	{"world 2",	"world 2"},
	{"world 3",	"world 3"},
	{"world 4",	"world 4"},
	{"world 5",	"world 5"},
	{"world 6",	"world 6"},
	{"world 7",	"world 7"},
	{"world 8",	"world 8"},
	{"world 9",	"world 9"},
	{"world 10",	"world 10"},
	{"world 11",	"world 11"},
	{"world 12",	"world 12"},
	{"world 13",	"world 13"},
	{"world 14",	"world 14"},
	{"world 15",	"world 15"},
	{"world 16",	"world 16"},
	{"world 17",	"world 17"},
	{"world 18",	"world 18"},
	{"world 19",	"world 19"},
	{"world 20",	"world 20"},
	{"world 21",	"world 21"},
	{"world 22",	"world 22"},
	{"world 23",	"world 23"},
	{"world 24",	"world 24"},
	{"world 25",	"world 25"},
	{"world 26",	"world 26"},
	{"world 27",	"world 27"},
	{"world 28",	"world 28"},
	{"world 29",	"world 29"},
	{"world 30",	"world 30"},
	{"world 31",	"world 31"},
	{"world 32",	"world 32"},
	{"world 33",	"world 33"},
	{"world 34",	"world 34"},
	{"world 35",	"world 35"},
	{"world 36",	"world 36"},
	{"world 37",	"world 37"},
	{"world 38",	"world 38"},
	{"world 39",	"world 39"},
	{"world 40",	"world 40"},
	{"world 41",	"world 41"},
	{"world 42",	"world 42"},
	{"world 43",	"world 43"},
	{"world 44",	"world 44"},
	{"world 45",	"world 45"},
	{"world 46",	"world 46"},
	{"world 47",	"world 47"},
	{"world 48",	"world 48"},
	{"world 49",	"world 49"},
	{"world 50",	"world 50"},
	{"world 51",	"world 51"},
	{"world 52",	"world 52"},
	{"world 53",	"world 53"},
	{"world 54",	"world 54"},
	{"world 55",	"world 55"},
	{"world 56",	"world 56"},
	{"world 57",	"world 57"},
	{"world 58",	"world 58"},
	{"world 59",	"world 59"},
	{"world 60",	"world 60"},
	{"world 61",	"world 61"},
	{"world 62",	"world 62"},
	{"world 63",	"world 63"},
	{"world 64",	"world 64"},
	{"world 65",	"world 65"},
	{"world 66",	"world 66"},
	{"world 67",	"world 67"},
	{"world 68",	"world 68"},
	{"world 69",	"world 69"},
	{"world 70",	"world 70"},
	{"world 71",	"world 71"},
	{"world 72",	"world 72"},
	{"world 73",	"world 73"},
	{"world 74",	"world 74"},
	{"world 75",	"world 75"},
	{"world 76",	"world 76"},
	{"world 77",	"world 77"},
	{"world 78",	"world 78"},
	{"world 79",	"world 79"},
	{"world 80",	"world 80"},
	{"world 81",	"world 81"},
	{"world 82",	"world 82"},
	{"world 83",	"world 83"},
	{"world 84",	"world 84"},
	{"world 85",	"world 85"},
	{"world 86",	"world 86"},
	{"world 87",	"world 87"},
	{"world 88",	"world 88"},
	{"world 89",	"world 89"},
	{"world 90",	"world 90"},
	{"world 91",	"world 91"},
	{"world 92",	"world 92"},
	{"world 93",	"world 93"},
	{"world 94",	"world 94"},
	{"world 95",	"world 95"},
	{"[0]",	"[0]"},
	{"[1]",	"[1]"},
	{"[2]",	"[2]"},
	{"[3]",	"[3]"},
	{"[4]",	"[4]"},
	{"[5]",	"[5]"},
	{"[6]",	"[6]"},
	{"[7]",	"[7]"},
	{"[8]",	"[8]"},
	{"[9]",	"[9]"},
	{"[.]",	"[.]"},
	{"[/]",	"[/]"},
	{"[*]",	"[*]"},
	{"[-]",	"[-]"},
	{"[+]",	"[+]"},
	{"enter",	"enter"},
	{"equals",	"equals"},
	{"up",	"up"},
	{"down",	"down"},
	{"right",	"right"},
	{"left",	"left"},
	{"insert",	"insert"},
	{"home",	"home"},
	{"end",	"end"},
	{"page up",	"page up"},
	{"page down",	"page down"},
	{"f1",	"f1"},
	{"f2",	"f2"},
	{"f3",	"f3"},
	{"f4",	"f4"},
	{"f5",	"f5"},
	{"f6",	"f6"},
	{"f7",	"f7"},
	{"f8",	"f8"},
	{"f9",	"f9"},
	{"f10",	"f10"},
	{"f11",	"f11"},
	{"f12",	"f12"},
	{"f13",	"f13"},
	{"f14",	"f14"},
	{"f15",	"f15"},
	{"numlock",	"numlock"},
	{"caps lock",	"caps lock"},
	{"scroll lock",	"scroll lock"},
	{"right shift",	"right shift"},
	{"left shift",	"left shift"},
	{"right ctrl",	"right ctrl"},
	{"left ctrl",	"left ctrl"},
	{"right alt",	"right alt"},
	{"left alt",	"left alt"},
	{"right meta",	"right meta"},
	{"left meta",	"left meta"},
	{"", ""}
};
