[package]
name = "landgen"
version = "0.1.0"
authors = ["Andrey Korotaev <a.korotaev@hedgewars.org>"]
edition = "2018"

[dependencies]
integral-geometry = { path = "../integral-geometry" }
land2d = { path = "../land2d" }
itertools = "0.7.8"
