#! /bin/bash

#USER DEFINES
ANDROID_NDK=/home/richard/SoftDev/android/android-ndk-r5b

#END USER DEFINES

cd SDL-android-project
$ANDROID_NDK/ndk-build
if [ $? -ne 0 ] 
then 
  echo "Failed to execute $ANDROID_NDK/ndk-build"
  exit 1
fi
cd ..
make -f Makefile.android
if [ $? -ne 0 ] 
then 
  echo "Failed to execute make -f Makefile.android"
  exit 1
fi
cd SDL-android-project
ant install
if [ $? -ne 0 ] 
then 
  echo "Failed to execute ant install"
  exit 1
fi
exit 0 
