######################################################################
# Automatically generated by qmake (2.01a) ?? 23. ??? 20:44:46 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainform.h pixlabel.h
SOURCES += main.cpp mainform.cpp pixlabel.cpp
