[package]
name = "hedgewars-engine"
version = "0.1.0"
authors = ["Andrey Korotaev <a.korotaev@hedgewars.org>"]
edition = "2018"

[dependencies]
lib-hedgewars-engine = { path = "../lib-hedgewars-engine" }
libloading = "0.5.0"

